# Generated by Django 2.2.5 on 2019-10-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0005_auto_20191001_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='block',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'To Do'), (2, 'In Progress'), (3, 'Done')], default=0, verbose_name='Тип задачи'),
        ),
        migrations.DeleteModel(
            name='Block',
        ),
    ]
