# Generated by Django 2.2.5 on 2019-11-03 20:09

from django.db import migrations, models
import jira.utils


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0008_auto_20191103_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='taskdocument',
            name='document',
            field=models.FileField(upload_to='jira/documents/', validators=[jira.utils.validate_file_size, jira.utils.validate_extension], verbose_name='Документ'),
        ),
    ]
