# Generated by Django 2.2.5 on 2019-10-01 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0002_auto_20191001_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='name',
        ),
    ]
